# Generated by Django 5.2 on 2025-10-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("available", "Còn hàng"), ("out_of_stock", "Hết hàng")],
                default="available",
                max_length=20,
            ),
        ),
    ]
