# Generated by Django 5.2 on 2025-10-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_rename_category_product_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categories",
            new_name="category",
        ),
    ]
