# Generated by Django 5.2 on 2025-11-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
    ]
