# Generated by Django 5.2 on 2025-10-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="avatar",
        ),
    ]
