# Generated by Django 5.2 on 2025-10-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
