# Generated by Django 5.2 on 2025-11-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_floweritem_supplier_alter_inventory_product_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="product",
            new_name="flower",
        ),
    ]
