# Generated by Django 5.2 on 2025-11-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_goodsreceipt_goodsreceiptitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="floweritem",
            name="stock_bunches",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="floweritem",
            name="unit",
            field=models.CharField(default="bó", max_length=20),
        ),
    ]
