# Generated by Django 5.2 on 2025-11-07 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_floweritem_stock_bunches_alter_floweritem_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="floweritem",
            name="stems_per_bunch",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="goodsreceiptitem",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
