# Generated by Django 5.2 on 2025-11-07 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_floweritem_stems_per_bunch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowerCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                "verbose_name": "Danh mục hoa lẻ",
                "verbose_name_plural": "Các danh mục hoa lẻ",
            },
        ),
        migrations.AddField(
            model_name="floweritem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flowers",
                to="inventory.flowercategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="floweritem",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_bunches__gte", 0)),
                name="stock_bunches_non_negative",
            ),
        ),
    ]
