# Generated by Django 5.2 on 2025-11-07 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0007_flowercategory_floweritem_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goodsreceiptitem",
            name="flower",
        ),
        migrations.AddField(
            model_name="goodsreceiptitem",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptitem",
            name="object_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
