# Generated by Django 5.2 on 2025-11-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_remove_goodsreceiptitem_flower_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="total_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
