# Generated by Django 5.2 on 2025-10-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0003_remove_order_discount_amount_remove_order_order_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={
                "verbose_name": "Mã giảm giá",
                "verbose_name_plural": "Các mã giảm giá",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Đơn hàng",
                "verbose_name_plural": "Các đơn hàng",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Sản phẩm trong đơn hàng",
                "verbose_name_plural": "Sản phẩm trong đơn hàng",
            },
        ),
        migrations.AlterModelOptions(
            name="shippingarea",
            options={
                "verbose_name": "Khu vực giao hàng",
                "verbose_name_plural": "Các khu vực giao hàng",
            },
        ),
        migrations.AlterField(
            model_name="deliveryproof",
            name="image",
            field=models.ImageField(upload_to="delivery_proofs/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="order",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="qrcodes/%Y/%m/%d/"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shippingarea",
            unique_together={("city", "district")},
        ),
    ]
