# Generated by Django 5.2 on 2025-10-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_coupon_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
