# Generated by Django 5.2 on 2025-11-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_shipping_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
