# Generated by Django 5.2 on 2025-11-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_coupon_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
