# Generated by Django 5.2 on 2025-11-06 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryproof",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_proofs",
                to="orders.order",
            ),
        ),
    ]
