# Generated by Django 5.2 on 2025-11-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_deliveryproof_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("PAYPAL", "PayPal"), ("COD", "Thu tiền mặt (COD)")],
                default="COD",
                max_length=20,
                verbose_name="Phương thức thanh toán",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                choices=[("PICKUP", "Nhận tại cửa hàng"), ("DELIVERY", "Giao tận nơi")],
                default="PICKUP",
                max_length=20,
                verbose_name="Phương thức giao hàng",
            ),
        ),
    ]
